version: "3.7"

services:
  mysql:
    image: mysql:8.1
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: app
    ports:
      - 33306:3306

volumes:
  mysql-data: